name: EusMinerHat
main: skillter.eusminerhat.MinerHat
version: 1.0
api-version: 1.19
softdepend: [ Vault ]
authors: [ EucalyptusLeaves ]
website:
commands:
  minerhat:
  minerhatadmin:
permissions:
  minerhat.contributor:
    default: true
    description: Permission for MinerHat mining contributior commands
  minerhat.admin:
    default: op
    description: Permission for MinerHat management commands
